#!/usr/bin/python

DOMAIN = "mintnanny"
PATH = "/usr/share/linuxmint/locale"

import os, gettext, sys
sys.path.append('/usr/lib/linuxmint/common')
import additionalfiles

os.environ['LANG'] = "en_US.UTF-8"
gettext.install(DOMAIN, PATH)

prefix = "[Desktop Entry]\n"

suffix = """Exec=mintnanny
Icon=/usr/lib/linuxmint/mintNanny/icon.svg
Terminal=false
Type=Application
Encoding=UTF-8
Categories=Application;System;Settings;
StartupNotify=false
"""

additionalfiles.generate(DOMAIN, PATH, "usr/share/applications/mintNanny.desktop", prefix, _("Domain Blocker"), _("Block access to selected domain names"), suffix, genericName=_("Parental Control"))
