#!/bin/bash

intltool-extract --type=gettext/glade usr/share/linuxmint/mintnanny/mintnanny.ui

xgettext --language=Python --keyword=_ --output=mintnanny.pot \
  usr/lib/linuxmint/mintnanny/mintnanny.py \
  generate_desktop_files \
  usr/share/linuxmint/mintbackup/mintbackup.ui.h
xgettext --language=PolkitPolicy --its=polkit.its --output=mintnanny.pot --join-existing usr/share/polkit-1/actions/*.policy

rm -f usr/share/linuxmint/mintnanny/mintnanny.ui.h
