#!/bin/bash

intltool-extract --type=gettext/glade usr/share/linuxmint/mintnanny/mintnanny.ui

xgettext --language=Python --keyword=_ --output=mintnanny.pot \
  usr/lib/linuxmint/mintnanny/mintnanny.py \
  generate_desktop_files \
  usr/share/linuxmint/mintnanny/mintnanny.ui.h

rm -f usr/share/linuxmint/mintnanny/mintnanny.ui.h
